### ISSUE TITLE
feat: contrast option

### ISSUE THREAD

**Issue by qbedard** [Murtaza-Udaipurwala/gruvqueen#2]
The original gruvbox has a contrast option that can be soft, medium, or hard, of which the default is medium. The colors in this theme only seem to support something akin to hard at the moment.

**Comment by murtaza-u** [comment]
Gruvqueen has material, mix and original styles which acts as a replacement for the contrast options. The only thing that setting these styles donot change is the background color for which gruvqueen provides vim.g.gruvqueen_background_color option. For now I'll keep this feature implementation on low priority.
