### ISSUE TITLE
fix: original bg color wrong

### ISSUE THREAD

**Issue by qbedard** [Murtaza-Udaipurwala/gruvqueen#5]
The original background color should be bg0 (#282828).

gruvbox medium (technically gruvbox.nvim, but they match):
<img width="400" alt="Screen Shot 2021-08-02 at 11 21 25 AM" src="https://user-images.githubusercontent.com/1565211/127893062-21311c29-d3ad-4ab5-86f1-77066d20719a.png">

gruvbox hard:
<img width="408" alt="Screen Shot 2021-08-02 at 11 18 31 AM" src="https://user-images.githubusercontent.com/1565211/127892845-f8d08d00-54a5-4939-ad59-6e592460d863.png">

gruvqueen:
<img width="399" alt="Screen Shot 2021-08-02 at 11 18 49 AM" src="https://user-images.githubusercontent.com/1565211/127892868-9080a6e1-114e-454a-9842-a060e8052c5d.png">

**Comment by murtaza-u** [comment]
This is a well thought modification to the original gruvbox palette. In my opinion this makes gruvqueen look a 1000 times more appealing. However users are not restricted to using this background color, hence the option to change the bg color is provided. There are also other modification done to the original colorscheme such as the colors of active line number,  completion menu, etc.

**Comment by qbedard** [comment]
I disagree on the appeal as I prefer the lower contrast, but I'll just change/disable the background color. I also use gruvbox as a theme for more than Neovim, so I want everything to match.

**Comment by qbedard** [comment]
The line number bothers me less, but oof that completion menu is pretty off-palette. 😬
<img width="405" alt="Screen Shot 2021-08-02 at 1 20 18 PM" src="https://user-images.githubusercontent.com/1565211/127906378-b3857c9e-e7cb-4e44-a612-7ecca639b31e.png">
Really blue.

**Comment by murtaza-u** [comment]
@timbedard I have come to realise that the completion menu is actually **really blue**. I have changed it to something more towards the grey side.
