### ISSUE TITLE
fix: `:set background=light` doesn't change colors

### ISSUE THREAD

**Issue by qbedard** [Murtaza-Udaipurwala/gruvqueen#6]
Having the light mode now is rad, but similar to #3, you still have to change it in the config and reload for it to have an effect. You should be able to `:set background=light` while running and have the colors change accordingly.

**Comment by murtaza-u** [comment]
My bad! I seperated out stuff into different functions but forgot to actually call it.

**Comment by murtaza-u** [comment]
@timbedard thanks for pointing it out
