### ISSUE TITLE
unreadable error msgs

### ISSUE THREAD

**Issue by danielnehrig** [Murtaza-Udaipurwala/gruvqueen#7]
```lua
        config = function()
            if not vim.g.neovide then
                vim.g.gruvqueen_transparent_background = true
            else
                vim.g.gruvqueen_transparent_background = false
            end
            vim.g.gruvqueen_background_color = "#10151a"
            vim.g.gruvqueen_italic_comments = true
            vim.g.gruvqueen_italic_keywords = true
            vim.g.gruvqueen_italic_functions = true
            vim.g.gruvqueen_italic_variables = true
            vim.g.gruvqueen_invert_selection = true
            vim.g.gruvqueen_style = "mix" -- possible values: 'original', 'mix', 'material'

            vim.cmd("colorscheme gruvqueen")
        end
```

if i get a error msg at the bottom it has a fg value of red and a bg value of red
which makes it extremely hard to read

![image](https://i.imgur.com/PQux6zn.png)

**Comment by murtaza-u** [comment]
@danielnehrig the latest commit has fixed this issue.  I have changed the background color of error message to NONE. Hence it will now default to the `Normal` background color(which is `#10151a` by default).

![2021-09-10-@16-03-07](https://user-images.githubusercontent.com/75304812/132840804-e8fe03aa-8e00-4712-a400-d2a3017e4c92.png)

Sorry for the late reply.

Thankyou

**Comment by danielnehrig** [comment]
can confirm works like it should
thanks for the fast fix
