### ISSUE TITLE
feat: make signcolumn bg transparent if transparent mode is set

### ISSUE THREAD

**Issue by danielnehrig** [Murtaza-Udaipurwala/gruvqueen#8]
Should apply also to gitsigns, diagnostic signs etc.

**Comment by murtaza-u** [comment]
Yes. I think I should set their background to `NONE` irrespective of transparent mode. That way it will simply default to the `Normal` background color.
Feels more uniform that way.

**Comment by murtaza-u** [comment]
@danielnehrig the feat has been added to master branch. You can close this issue if you want to.
